#!/bin/bash

CPATH=`pwd`
ksdir=~/work/debug/ksnapshot

#color define
S_COLOR='\e[1;33m'
E_COLOR='\e[1;31m'
I_COLOR='\e[1;34m'
L_COLOR='\e[1;36m'
RES='\E[0m'

#Add spaces to the string to make one option per line when selecting
chgexit='[EXIT (-_-) ]'
gotoup='[Go up <<<< ]'
sshvm='vm login'
killvm='vm close'
restartvm='vm restart'
moreinfo='vm info'
vmcore='save core'
vmsavelog='save log'
flush='[vm update]'
vmlog='vm log'
vmtop='[vm top]'

ipprefix="192.168.22."
qemu_prefix="qemu-"


fun_getvm() {
	unset lines
	unset types
	unset ips
	unset uptime
	unset status
	unset sshs
	local i
	readarray -t lines < <(ps ux | grep ${qemu_prefix} | grep -v grep)
	count=${#lines[@]}
	echo -e "${S_COLOR}---------------------------------------------------------------------------"
	echo -e "You have ${E_COLOR}$count${S_COLOR} virtual machines running >>"
	printf "%-15s| %-4s| %-10s| %-10s| %-12s| %-4s|\n" "Network" "Sel" "Arch" "PID" "UpTime" "SSH"
	for (( i=0; i<$count; i++))
	do
		types[$i]=`echo "${lines[i]}" | awk -F "system-" '{print $2}' | awk -F " " '{print $1}'`
		pids[$i]=`echo "${lines[i]}" | awk '{print $2}'`
		ips[$i]=`echo "${lines[i]}" | awk -F "IP=" '{print $2}' | awk -F " " '{print $1}'`
		ports[$i]=`echo "${lines[i]}" | awk -F "localhost:" '{print $2}' | awk -F "," '{print $1}'`
		#uptime[$i]=`ps -o etime -p ${pids[$i]} | grep -v ELAPSED`
		uptime[$i]="0"
		#sshs[$i]=`ps ux | grep "ssh " | grep -v grep | grep -v sshpass | grep ${ips[$i]} |wc -l`
		sshs[$i]="0"
		num="$(( $i + 4 ))"
		printf "${L_COLOR}%-15s${S_COLOR}|${L_COLOR} %-4d${S_COLOR}| %-10s| %-10s| %-12s| %-4s|\n" \
			"${ips[$i]}" $num "${types[$i]}" "${pids[$i]}" "${uptime[$i]}" "${sshs[$i]}" 
	done
	echo -e "${S_COLOR}---------------------------------------------------------------------------"
}

fun_getvmtop() {
	unset lines
	unset types
	unset ips
	unset uptime
	unset status
	unset sshs
	local i
	readarray -t lines < <(ps ux | grep ${qemu_prefix} | grep -v grep)
	count=${#lines[@]}
	printf "\033c" #clear terminal
	echo -e "${S_COLOR}---------------------------------------------------------------------------"
	echo -e "You have ${E_COLOR}$count${S_COLOR} virtual machines running >>"
	printf "%-8s| %-15s| %-10s| %-10s| %-12s| %-4s|\n" "Staus" "Network" "Arch" "PID" "UpTime" "SSH"
	for (( i=0; i<$count; i++))
	do
		types[$i]=`echo ${lines[i]} | awk -F "system-" '{print $2}' | awk -F " " '{print $1}'`
		pids[$i]=`echo ${lines[i]} | awk -F " " '{print $2}'`
		ips[$i]=`echo ${lines[i]} | awk -F "IP=" '{print $2}' | awk -F " " '{print $1}'`
		uptime[$i]=`ps -o etime -p ${pids[$i]} | grep -v ELAPSED`
		sshs[i]=`ps ux | grep "ssh " | grep -v grep | grep -v sshpass | grep ${ips[$i]} |wc -l`
		ping ${ips[$i]} -c 1 -W 1 > /dev/null
		if [ $? == 0 ] ;then
			status[$i]="Alive"
		else
			status[$i]="....."
			ping ${ips[$i]} -c 1 -W 1 > /dev/null && status[$i]="Alive"
		fi

		printf "%-8s| %-15s| %-10s| %-10s| %-12s| %-4d|\n" ${status[$i]} ${ips[$i]} \
			${types[$i]} ${pids[$i]} ${uptime[$i]} ${sshs[$i]} 
	done
	echo -e "${S_COLOR}---------------------------------------------------------------------------"
}

# 登陆qemu生成vmcore文件
fun_savecore() {
	local index=$1
	local datetag=$2
	local qemuport="localhost ${ports[$index]}"
	local tmpdir=/tmp/ll_tmp
	local tmpfile=${tmpdir}/qemu_vmcore.img
	local tailip=`echo ${ips[$index]} | awk -F "." '{print $4}'`
	local corefile=${CPATH}/qemu_vm_t${tailip}_${datetag}.core

	echo -e "${L_COLOR}Start generate vmcore for ${ips[$index]}......"
	if [ ! -d $tmpdir ] ;then
		mkdir -p $tmpdir
	fi
	if [ -f $tmpfile ] ;then
		rm $tmpfile -f
	fi

	{
		sleep 0.5
		echo '{"execute": "qmp_capabilities"}'
		sleep 0.5
		echo '{"execute":"dump-guest-memory","arguments":{"paging":false,"protocol":"file:/tmp/ll_tmp/qemu_vmcore.img"}}'
		sleep 1
		echo -e '\035'
		sleep 0.5
		echo 'quit'
	}|telnet $qemuport

	if [ $? == 0 ] ;then
		cp $tmpfile $corefile
		if [ -f $tmpfile ] ;then
			rm $tmpfile -f
		fi
		echo -e "${L_COLOR}Success generate vmcore: ${I_COLOR}${corefile}"
		echo -e "${RES}"
	else
		echo -e "${E_COLOR}Failed generate vmcore.${RES}"
	fi
}

func_savelog() {
	local index=$1
	local datetag=$2
	local tailip=`echo ${ips[$index]} | awk -F "." '{print $4}'`
	logfile=`echo ${lines[$index]} | awk -F "serial file:" '{print $2}' | awk -F " " '{print $1}'`
	local vmlogfile=${CPATH}/qemu_vm_t${tailip}_${datetag}.log

	if [ -z $logfile ] ;then
		echo -e "${E_COLOR}Virtual machine ${ips[$index]} log ${logfile} not exist."
	else
		cp $logfile $vmlogfile
		echo -e "${L_COLOR}Success save log: ${I_COLOR}${vmlogfile}"
	fi
	echo -e "${RES}"
}

# 根据虚拟机的kernel镜像匹配ksnapshot快照
func_linkksnap() {
	local index=$1
	local datetag=$2
	local tailip=`echo ${ips[$index]} | awk -F "." '{print $4}'`
	local kimage=`echo ${lines[$index]} | awk -F "-kernel " '{print $2}' | awk -F " " '{print $1}'`
	local vmsnapshot=${CPATH}/qemu_vm_t${tailip}_${datetag}.ksnap
	unset snapdirs
	readarray -t snapdirs < <(ls `realpath $ksdir`)

	for element in ${snapdirs[@]}
	do
		[[ -d $ksdir/$element ]] || continue
		[[ -f $ksdir/$element/bzImage ]] || continue
		diff $ksdir/$element/bzImage $kimage >> /dev/null
		if [ $? == 0 ] ;then
			ln -s $ksdir/$element $vmsnapshot
			echo -e "${L_COLOR}Success find ksnapshot: ${I_COLOR}$ksdir/$element"
			return 0
		fi
	done
	echo -e "${E_COLOR}Not find ksnapshot"
	return 1
}

fun_vmctrl() {
	local index=$1
	ping ${ips[$index]} -c 1 -W 1 > /dev/null
	if [ $? == 0 ] ;then
		status[$index]="Connect"
	else
		status[$index]="Disconn"
	fi
	sshs[$index]=`ps ux | grep "ssh " | grep -v grep | grep -v sshpass | grep ${ips[$index]} |wc -l`
	while true;do
		echo -e "${S_COLOR}---------------------------------------------------------------------------"
		echo -e "${S_COLOR}The virtual machine that you currently selected >>"
		printf "%-15s| %-10s| %-10s| %-12s| %-10s| %-4s|\n" "Network" "Arch" "PID" "UpTime" "Status" "SSH"
		printf "${L_COLOR}%-15s${S_COLOR}| %-10s| %-10d| %-12s| %-10s| %-4d|\n" ${ips[$index]} \
			${types[$index]} ${pids[$index]} ${uptime[$index]} ${status[$index]} ${sshs[$index]}
		echo -e "${S_COLOR}---------------------------------------------------------------------------"
		echo -e "Plese enter operation number:"
		select vm in "${chgexit}" "${gotoup}" "${sshvm}" "${killvm}" "${moreinfo}" "${vmlog}" "${vmsavelog}" "${vmcore}";
		do
			case $vm in
				"${chgexit}")
					echo -e "${RES}"
					exit
					;;
				"${gotoup}")
					echo -e "${RES}"
					break 2
					;;
				"${sshvm}")
					if [ ${status[$index]} == "Connect" ] ;then
						echo -e "SSH ${ips[$index]}......"
						echo -e "${RES}"
						sshpass -p "root" ssh root@${ips[$index]} -o StrictHostKeyChecking=no
						if [ $? != 0 ] ;then
							echo -e "${E_COLOR}SSH login ${ips[$index]} faild."
						fi
					else
						echo -e "${E_COLOR}Can't connecting to ${ips[$index]}"
					fi
					echo -e "${RES}"
					break
					;;
				"${killvm}")
					local tailip=`echo ${ips[$index]} | awk -F "." '{print $4}'`
					vmmutil -o stop -i ${tailip}
					break 2
					;;
				"${moreinfo}")
					#sed以" -"来分隔一行为多行, readarray可以以行来分隔读取到数组
					readarray -t params < <(echo ${lines[$index]} | awk -F "qemu-" '{print $2}' | sed 's/ -/\n/g')
					echo -e "${I_COLOR}---------------------------------------------------------------------------"
					echo -e "Virtual machine options >>"
					nparams=${#params[@]}
					for (( i=1; i<$nparams; i++))
					do
						echo "-${params[$i]}"
					done
					echo -e "${I_COLOR}---------------------------------------------------------------------------"
					echo -e "${RES}"
					break
					;;
				"${vmlog}")
					echo -e "${RES}"
					unset logfile
					logfile=`echo ${lines[$index]} | awk -F "serial file:" '{print $2}' | awk -F " " '{print $1}'`
					if [ -z $logfile ] ;then
						echo -e "${E_COLOR}Virtual machine ${ips[$index]} log ${logfile} not exist."
					else
						less $logfile
					fi
					echo -e "${RES}"
					break
					;;
				"${vmsavelog}")	
					local datetag=`date '+%Y%m%d_%H%M%S'`
					func_savelog $index $datetag
					break
					;;
				"${vmcore}")
					local datetag=`date '+%Y%m%d_%H%M%S'`
					fun_savecore $index $datetag
					func_savelog $index $datetag
					func_linkksnap $index $datetag
					break
					;;
		
				*)
					break
					;;
			esac
		done
	done
}

fun_vmtop() {
	local i
	while true;do
		fun_getvmtop
		for (( i=0; i<10; i++))
		do
			read -r -t 1 -N 1 input
				case $input in
				[eE]|[qQ])
				break 2
				;;
			esac
		done
	done
}

fun_main() {
	while true;do
	fun_getvm
	echo -e "Plese enter select number:"
	select vm in "${chgexit}" "${flush}" "${vmtop}" "${ips[@]}" ;
	do
		case $vm in
			"${chgexit}")
				echo -e "${RES}"
				exit
		;;
				"${flush}")
				echo -e "${RES}"
				break
		;;
				"${vmtop}")
				fun_vmtop
				echo -e "${RES}"
				break
		;;
			*)
				selectip=$vm 
				if [ -z $selectip ] ;then
					break
				fi
				for (( i=0; i<$count; i++)) 
				do
					if [ ${ips[$i]} = $selectip ] ;then
						fun_vmctrl $i
					fi	
				done
			break
		;;

	esac
	done
	done
}

fun_login() {
	local tail i n
	tail=$1
	if [[ $tail =~ ^[0-9]+$ ]] ;then
		fun_getvm
		n=${#ips[@]}
		for (( i=0; i<$n; i++))
		do
			if [ $ipprefix$tail == ${ips[$i]} ] ;then
				fun_vmctrl $i
				exit 0
			fi
		done
	else
		echo -e "tail ip in correct"
	fi
}


#main
if [ $# != 0 ] ; then
	fun_login $1
else
	fun_main
fi
